In [9]:
import pandas as pd

CSV_PATH = './pg_catalog.csv'

csv = pd.read_csv(CSV_PATH, index_col=0)

# get unique subjects
subjects = csv['Subjects'].unique()
for subject in subjects:
    if 'math' in str(subject).lower():
        print(subject)

# get unique bookshelves
shelves = csv['Bookshelves'].unique()
for shelf in shelves:
    if 'math' in str(shelf).lower():
        print(shelf)

Mathematics; Pi
Mathematics; Square root
Mathematics; Mathematical constants
Mathematics; Numbers, Prime
Mathematics; Factorials
Mathematics
Mathematics; Fibonacci numbers
Mathematics; Mathematical constants; Golden section
Mathematical constants
Mathematics; Bernoulli numbers
Square root; Mathematics -- Humor
Logic, Symbolic and mathematical; Logic -- Juvenile literature
Mathematics; Physics
Poetry; Grail -- Legends; Joseph, of Arimathea, Saint -- Legends
Logic, Symbolic and mathematical; Language and languages -- Philosophy
Abel, Niels Henrik, 1802-1829; Mathematicians -- Biography
Mathematics -- History
Mathematicians -- Great Britain -- Biography; Mathematics -- Great Britain -- History -- 19th century
Logic, Symbolic and mathematical; Algebraic logic
Authors, English -- 19th century -- Biography; Carroll, Lewis, 1832-1898; Children -- Books and reading -- Great Britain -- History -- 19th century; Mathematics teachers -- Great Britain -- Biography; Mathematicians -- Great Britain -- Biography; Photographers -- Great Britain -- Biography; Children's literature -- Authorship; Fantasy literature -- Authorship; Oxford (England) -- Biography
Mathematics; Algebra
Mathematics, Chinese -- Early works to 1800
Logic, Symbolic and mathematical; Probabilities; Thought and thinking
Mathematics; Mathematical physics
Word problems (Mathematics); Mathematics -- Problems, exercises, etc.
Mathematical recreations; Puzzles
Mathematics; Circle; Sphere; Geometry, Analytic
Algebra; Mathematics -- History
Cardano, Girolamo, 1501-1576; Mathematicians -- Biography
Euclid's Elements; Mathematics, Greek
Geometry -- Early works to 1800; Philosophy -- Early works to 1800; Mathematics -- Early works to 1800
Mathematics, Chinese -- Early works to 1800; Arithmetic -- Early works to 1900
Hyperspace; Magic squares; Mathematics -- Philosophy; Circle-squaring
Mathematics; Science; Philosophy
Mathematics -- History; Arithmetic -- Early works to 1900; Algorithms
Mathematical physics; Quaternions
Geometry -- Early works to 1800; Mathematics -- Early works to 1800
Numbers, Prime; Astrology; Matter; Mathematical recreations; Geometry -- Famous problems; Cryptography; Ciphers; Space and time; Magic squares; University of Cambridge -- History; Mathematics -- Study and teaching -- England -- Cambridge
Mather, Cotton, 1663-1728; Witchcraft -- Massachusetts -- Salem -- History -- 17th century; Salem (Mass.) -- History -- Colonial period, ca. 1600-1775
Calculators; Mathematical instruments
Logic, Symbolic and mathematical
Mathematical recreations
Mathematics -- Periodicals
Mathematical geography
Potential theory (Mathematics)
Mathematical physics; Integral equations
Mathewson, Christy, 1880-1925; Pitching (Baseball); Baseball -- United States -- History
Science fiction; Artificial intelligence -- Fiction; Blind women -- Fiction; Women mathematicians -- Fiction; Implants, Artificial -- Fiction; World Wide Web -- Fiction
Science -- Philosophy; Mathematics -- Philosophy
Transformations (Mathematics); Continuous groups
Mathematicians -- Biography; Appell, Paul, 1855-1930; Appell, Paul, 1855-1930 -- Bibliography
Calculus, Integral; Variables (Mathematics)
Algebra; Geometry; Mathematics -- Study and teaching
Mathematics -- Philosophy
Science -- Methodology; Science -- Philosophy; Mathematics -- Philosophy
Quotations; Quotations, French; Mathematicians; Mathematicians -- France; Mathematics -- France -- Quotations, maxims, etc.; Mathematics -- Quotations, maxims, etc.
Mathematicians -- Biography; Darboux, Gaston, 1842-1917
Mathematics; Mathematics -- Quotations, maxims, etc.
Mathematicians -- Biography; Oughtred, William, 1575-1660; Mathematics -- Study and teaching -- History -- 17th century
Caroline Mathilde, Queen, consort of Christian VII, King of Denmark, 1751-1775; Denmark -- History -- Christian VII, 1766-1808
Wrede, Mathilda, 1864-1928
Mathematics -- Early works to 1800; Science -- Early works to 1800; Physics -- Early works to 1800; Newton, Isaac, Sir, 1642-1727
Caroline Mathilde, Queen, consort of Christian VII, King of Denmark, 1751-1775
Amusements; Mathematical recreations; Puzzles
Crystallography, Mathematical
Mathematicians -- Biography; Scot, Michael, approximately 1175-approximately 1234; Astronomers -- Biography
Science -- Methodology; Logic, Symbolic and mathematical; Probabilities; Chance
Mathematicians -- Great Britain -- Biography; Babbage, Charles, 1791-1871
Mathematics -- History; Civilization, Ancient; Mathematics, Ancient
Yurok Indians; Klamath Indians
Mathematics
Science Fiction; Mathematics
Mathematics; Physics
Philosophy; Mathematics; DE Sachbuch
Philosophy; Mathematics
Mathematics; DE Sachbuch
Mathematics; Physics; DE Sachbuch
Mathematics; FR Sciences et Techniques
Early English Text Society; Mathematics
FR Po√©sie; Mathematics; FR Sciences et Techniques
Best Books Ever Listings; Mathematics; Physics
Astronomy; Mathematics

C:\Users\Xu kangping\AppData\Local\Temp\ipykernel_71576\3230421310.py:5: DtypeWarning: Columns (8) have mixed types. Specify dtype option on import or set low_memory=False.
  csv = pd.read_csv(CSV_PATH, index_col=0)

In [12]:
csv.describe()

,Type,Issued,Title,Language,Authors,Subjects,LoCC,Bookshelves
count,71178,71178,71178,71178,71008,71115,70921,17168
unique,7,7095,69565,112,34085,39925,1314,1267
top,Text,2004-02-01,Poems,en,Various,Fiction,PS,Science Fiction
freq,69927,672,66,57332,2704,1406,10809,1173

In [10]:
# find all with math in subjects or bookshelves
math_csv = csv[csv['Subjects'].str.contains('math', case=False) | csv['Bookshelves'].str.contains('math', case=False)]

In [11]:
math_csv.describe()

,Type,Issued,Title,Language,Authors,Subjects,LoCC,Bookshelves
count,194,194,194,194,192,194,194,166
unique,2,162,191,9,154,142,25,19
top,Text,1996-08-01,"The Number ""e""",en,"Bonnell, Jerry T.; Nemiroff, Robert J.",Mathematics,QA,Mathematics
freq,181,8,2,140,9,10,143,95